Rewrite
hercules-ci/fastspring pull request #1
Opened 2019-02-08 09:09 UTC by domenkozar

Tried my best to split into commits, but included all the cabal and readme changes in the very last one.

2019-02-08 10:22 UTC, roberth commented on src/FastSpring/Client.hs
> +mkClient :: ClientM a -> IO (Either ServantError a)
`runClient manager cmd`

2019-02-08 10:26 UTC, roberth commented on src/FastSpring/UnixTimeMili.hs
> +newtype UnixTimeMili =
`UnixTimeMillis`, `UnixTimeMilliSeconds`, or at least spell with two `l`'s

2019-02-08 10:26 UTC, roberth commented on src/FastSpring/UnixTimeMili.hs
> +newtype UnixTimeMili =
Also comment should be haddock and point out that it's for serialization purposes

2019-02-08 10:27 UTC, roberth commented on src/FastSpring/WebHook/Event.hs
> +      --"subscription.deactivated" -> SubscriptionDeactivated <$> parseData
umm

2019-02-08 10:30 UTC, roberth commented on src/FastSpring/WebHook/Signature.hs
> +  { unwrapSecret :: ByteString
`SignatureSecret { unwrapSecret = ... }` is weird. You can use `coerce` to unwrap, so you might as well use positional syntax.

2019-02-08 11:02 UTC, domenkozar commented on src/FastSpring/WebHook/Event.hs
> +      --"subscription.deactivated" -> SubscriptionDeactivated <$> parseData
Missing todo :)

2019-02-10 05:31 UTC, domenkozar commented
@roberth I've addressed your comments.

2019-02-10 05:44 UTC, roberth requested changes

2019-02-10 05:44 UTC, roberth commented on src/FastSpring/WebHook/Signature.hs
> +-- useful for logging
Instances can have haddock. I am assuming this is not part of the FastSpring API? How is it rendered? (all non-Generic *JSON instances should document that)

2019-02-10 05:44 UTC, roberth commented on src/FastSpring/WebHook/Signature.hs
> +  (Signature l) == (Signature r) = l `constEq ` r
:heart: but please share this with the user via haddock

2019-02-10 06:01 UTC, domenkozar commented
@roberth second round, added haddock docs.

2019-02-10 06:23 UTC, roberth approved these changes

2019-02-10 06:34 UTC, merged